version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend