spring:
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:45842/railway
    username: root
    password: BbaGC3GAf51FC2-BBfEdCCbcHd5a-df3
  devtools:
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
file:
  upload-dir: src/main/resources/images
server:
  address: 0.0.0.0
  port: 5000
