spring:
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:16404/railway
    username: root
    password: FBEE2cccFCFAcGe55hdfD1DAahbGgC1F
  devtools:
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
file:
  upload-dir: src/main/resources/images
server:
  port: 5000